### ISSUE TITLE
LOOP

### ISSUE THREAD

**Issue by bluebutgreen** [karamana/web8085#1]
If a command is written in front of a loop like:
loop: <command>
then it causes issues. Please look into this. Won't take much effort to solve

**Comment by karamana** [comment]
I will take a look at it and get back to you.  Thank you for reporting the issue.

**Comment by karamana** [comment]
Prashant,

I think the issue is that you have is that the loop and the command in the same line.  You have to put the loop label in its own separate line.  Following is the example.

# The following will not work.
loop:  mov a,b

You have to change it into two lines.
# The following works
loop:
mov a,b
